### ISSUE TITLE
Missing jar in web folder

### ISSUE THREAD

**Issue by joshmc82** [odoodo/Mirth-Migrator#9]
The install instructions mention the jar file being in the web folder and just to copy the whole web folder into the Mirth Connect install directory. When I download the tagged release version, there is no jar in the web folder.

**Comment by odoodo** [comment]
You have to download the [7-Zip archive.](https://github.com/odoodo/Mirth-Migrator/releases/download/1.0/MirthMigrator.7z) This archive contains all needed files including the jar and installation instructions.

The zip files are just the packaged source code. This is automatically created by GitHub when a release is issued.
